version: 1.0.{build}

image:
  - Visual Studio 2019

install:
  - cinst OpenCppCoverage
  - cinst codecov
  - refreshenv

configuration:
  - Debug
  - Release

before_build:
  - cmake -H. -B./build -DBOOST_ROOT="C:/Libraries/boost_1_73_0"

test_script:
  - cd build
  - ctest -C %CONFIGURATION% --output-on-failure

after_test:
  - OpenCppCoverage --cover_children --sources=%APPVEYOR_BUILD_FOLDER% --export_type=cobertura:cobertura.xml -- ctest -C %CONFIGURATION%
  - codecov --no-color -f cobertura.xml
