version: 1.0.{build}

environment:
  matrix:
    - compiler: clang
      cmake_options: -G Ninja -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_CXX_COMPILER=clang-cl

    - compiler: msvc

install:
  - cinst OpenCppCoverage
  - cinst codecov
  - cinst ninja
  - refreshenv

image:
  - Visual Studio 2019

configuration:
  - Debug
  - Release

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - mkdir build && cd build
  - cmake %CMAKE_OPTIONS% -DBOOST_ROOT="C:/Libraries/boost_1_73_0" -DENABLE_DOCUMENTATION=OFF "%APPVEYOR_BUILD_FOLDER%"

build:
  project: build/boost-wintls.sln

for:
  -
    matrix:
      only:
        - compiler: clang
    build_script:
      - ninja

test_script:
  - ctest -C %CONFIGURATION% --output-on-failure

after_test:
  - OpenCppCoverage --cover_children --sources="%APPVEYOR_BUILD_FOLDER%" --excluded_sources="%APPVEYOR_BUILD_FOLDER%\test" --export_type=cobertura:cobertura.xml -- ctest -C %CONFIGURATION%
  - codecov --no-color -f cobertura.xml
