version: 1.0.{build}

image:
  - Previous Visual Studio 2019

install:
  - cinst OpenCppCoverage
  - cinst codecov
  - refreshenv

configuration:
  - Debug
  - Release

environment:
  matrix:
  - TOOLSET: ""
  - TOOLSET: ClangCL

before_build:
  - cmake -H. -B./build -T "%TOOLSET%" -DBOOST_ROOT="C:/Libraries/boost_1_73_0"

build:
  project: build/boost-wintls.sln

test_script:
  - cd build
  - ctest -C %CONFIGURATION% --output-on-failure

after_test:
  - OpenCppCoverage --cover_children --sources=%APPVEYOR_BUILD_FOLDER% --export_type=cobertura:cobertura.xml -- ctest -C %CONFIGURATION%
  - codecov --no-color -f cobertura.xml
