on: [push]

jobs:
  generate_documentation:
    runs-on: ubuntu-latest
    name: Generate and publish HTML documentation to Github Pages
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate
      uses: ./doc/docker
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc/html
        CLEAN: true
