on: [push]
name: docs

jobs:
  generate_documentation:
    runs-on: ubuntu-latest
    name: Generate and publish HTML documentation to Github Pages
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get -yq install python3-sphinx python3-breathe doxygen libboost-dev libssl-dev
        mkdir build
        cmake -Bbuild -H.
        cmake --build build/ --target sphinx
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/doc/sphinx
        CLEAN: true
